# Deployment Configuration for Railway
# This file is automatically detected by Railway

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run build && npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
