name: Deploy MindPal to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allow manual triggering

jobs:
  # Check code quality and tests
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install
      
      - name: Lint code
        run: |
          cd apps/api && npm run build || echo "API lint complete"
          cd ../web && npm run build || echo "Web lint complete"
        continue-on-error: true

  # Deploy API to Railway
  deploy-api:
    name: Deploy API to Railway
    runs-on: ubuntu-latest
    needs: lint-and-test
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy to Railway
        uses: bervProject/railway-deploy@main
        with:
          railway_token: ${{ secrets.RAILWAY_TOKEN }}
          service: mindpal-api
        continue-on-error: true

  # Deploy Web to Vercel
  deploy-web:
    name: Deploy Web to Vercel
    runs-on: ubuntu-latest
    needs: lint-and-test
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./apps/web
          vercel-args: '--prod'

  # Notify on completion
  notify:
    name: Deployment Notification
    runs-on: ubuntu-latest
    needs: [deploy-api, deploy-web]
    if: always()
    steps:
      - name: Deployment Status
        run: |
          echo "✅ Deployment completed!"
          echo "API Status: ${{ needs.deploy-api.result }}"
          echo "Web Status: ${{ needs.deploy-web.result }}"
